{% set version = "0.9.39" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-clickr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/clickR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/clickR/clickR_{{ version }}.tar.gz
  sha256: cd94b4e306063c35d2f6277fd117e03c843d00f0ed81004e3378b520f91c1b4f

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-beeswarm
    - r-future
    - r-future.apply
    - r-stringdist
  run:
    - r-base
    - r-beeswarm
    - r-future
    - r-future.apply
    - r-stringdist

test:
  commands:
    - $R -e "library('clickR')"           # [not win]
    - "\"%R%\" -e \"library('clickR')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=clickR
  license: GPL-2.0-or-later
  summary: Tools for assessing data quality, performing exploratory analysis, fixing data errors in numerical, factor and date variables and creating report tables from models and summaries.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
